project_id       = "ei-catalog-stg"
region           = "us-central1"
runtime_sa_email = "ei-catalog-api@ei-catalog-stg.iam.gserviceaccount.com"
images_bucket    = "ei-catalog-images-stg"
environment      = "staging"
image            = "us-central1-docker.pkg.dev/ei-catalog-stg/ei-catalog/catalog-mx-catalog-api:latest"
