export { default as Button } from './components/Button.vue'
export { default as Badge } from './components/Badge.vue'
export { default as StatusBadge } from './components/StatusBadge.vue'
export { default as Card } from './components/Card.vue'
export { default as Input } from './components/Input.vue'
export { default as Skeleton } from './components/Skeleton.vue'
export { default as PriceDisplay } from './components/PriceDisplay.vue'
// Keep existing components
export { default as AppCard } from './components/AppCard.vue'
export { default as ThemePicker } from './components/ThemePicker.vue'
export { default as FeatureToggle } from './components/FeatureToggle.vue'
