project_id         = "ei-catalog-dev"
region             = "us-central1"
runtime_sa_email   = "ei-catalog-api@ei-catalog-dev.iam.gserviceaccount.com"
environment        = "development"
admin_notify_email = ""
smtp_host          = ""
smtp_port          = "587"
smtp_user          = ""
smtp_from          = ""
smtp_pass_secret   = "smtp-pass"
storefront_url     = "https://catalog.mx"
admin_url          = "https://admin.catalog.mx"

image              = "us-central1-docker.pkg.dev/ei-catalog-dev/ei-catalog/catalog-mx-notifications-webhook:latest"
