#!/usr/bin/env node
/**
 * SASS Factory — New App Scaffolder
 *
 * Usage:
 *   node infrastructure/scripts/new-app.mjs --topic=mom --name="Dia de las Madres" --slug=dia-madres-2024
 *
 * This script:
 *   1. Copies the template app to apps/<slug>
 *   2. Updates the .env with the app slug
 *   3. Creates the app config in Firestore (optional, requires --seed flag)
 */

import { execSync } from 'child_process'
import { existsSync, mkdirSync, cpSync, writeFileSync, readFileSync } from 'fs'
import { resolve, join } from 'path'
import { parseArgs } from 'util'

// Parse CLI args
const { values: args } = parseArgs({
  options: {
    topic: { type: 'string' },
    name: { type: 'string' },
    slug: { type: 'string' },
    status: { type: 'string', default: 'draft' },
    seed: { type: 'boolean', default: false },
    help: { type: 'boolean', default: false, short: 'h' },
  },
})

if (args.help) {
  console.log(`
SASS Factory — New App Scaffolder

Usage:
  node infrastructure/scripts/new-app.mjs [options]

Options:
  --topic=<topic>    Topic key (love, reyes, mom, dad, bday, xmas, or custom)
  --name=<name>      Display name for the app
  --slug=<slug>      URL slug (auto-generated from name if not provided)
  --status=<status>  Initial status: draft|active|archived (default: draft)
  --seed             Create Firestore entry after scaffolding
  -h, --help         Show this help

Examples:
  node infrastructure/scripts/new-app.mjs --topic=mom --name="Dia de las Madres"
  node infrastructure/scripts/new-app.mjs --topic=bday --name="Happy Birthday!" --slug=bday-alex --seed
`)
  process.exit(0)
}

// Validate required args
if (!args.topic) {
  console.error('❌ Error: --topic is required\n')
  console.error('Run with --help for usage info.')
  process.exit(1)
}

if (!args.name) {
  console.error('❌ Error: --name is required\n')
  console.error('Run with --help for usage info.')
  process.exit(1)
}

// Generate slug from name if not provided
const slug =
  args.slug ??
  args.name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 50)

const rootDir = resolve(process.cwd())
const templateDir = join(rootDir, 'apps', 'template')
const targetDir = join(rootDir, 'apps', slug)

console.log('\n✨ SASS Factory — Scaffolding new app\n')
console.log(`  Topic:  ${args.topic}`)
console.log(`  Name:   ${args.name}`)
console.log(`  Slug:   ${slug}`)
console.log(`  Status: ${args.status}`)
console.log(`  Target: apps/${slug}\n`)

// Check if template exists
if (!existsSync(templateDir)) {
  console.error(`❌ Template app not found at: ${templateDir}`)
  process.exit(1)
}

// Check if target already exists
if (existsSync(targetDir)) {
  console.error(`❌ App already exists at: ${targetDir}`)
  console.error('   Delete or rename it first.')
  process.exit(1)
}

// Copy template
console.log('📂 Copying template...')
cpSync(templateDir, targetDir, {
  recursive: true,
  filter: (src) => {
    // Skip node_modules, .nuxt, .output, dist
    const skip = ['node_modules', '.nuxt', '.output', 'dist', '.env']
    return !skip.some((s) => src.includes(`/${s}`))
  },
})

// Write .env file
const envContent = `# Generated by new-app.mjs
FIREBASE_API_KEY=
FIREBASE_AUTH_DOMAIN=
FIREBASE_PROJECT_ID=
FIREBASE_STORAGE_BUCKET=
FIREBASE_MESSAGING_SENDER_ID=
FIREBASE_APP_ID=

APP_SLUG=${slug}
APP_DOMAIN=
`
writeFileSync(join(targetDir, '.env'), envContent)
console.log('📝 Created .env file')

// Update package.json name
const pkgPath = join(targetDir, 'package.json')
if (existsSync(pkgPath)) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  pkg.name = slug
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
  console.log('📦 Updated package.json name')
}

console.log('\n✅ App scaffolded successfully!\n')
console.log('Next steps:')
console.log(`  1. cd apps/${slug}`)
console.log(`  2. Fill in your Firebase config in .env`)
console.log(`  3. pnpm install`)
console.log(`  4. pnpm dev`)

if (args.seed) {
  console.log('\n🌱 --seed flag detected, but Firestore seeding requires a service account.')
  console.log('   Run: npx ts-node infrastructure/firestore/seed.ts')
}

console.log()
